### ISSUE TITLE
Volume nupp alguses

### ISSUE THREAD

**Issue by sveeta** [rix133/amanda#1]
Sissejuhatuses on volume nupp vaikimisi maas. Äkki on loogiline, et see on vaikimisi sees?
Kui oled kord sellele vajutanud, on see läinud, ja ei saa enam heli välja lülitada
Kui lähed juba filmi sees olles tagasi Home'i, pole enam seda volume'i nuppu enam.

**Comment by rix133** [comment]
> Kui oled kord sellele vajutanud, on see läinud, ja ei saa enam heli välja lülitada

Selle võib ka alles jätta pole probleemi

> Kui lähed juba filmi sees olles tagasi Home'i, pole enam seda volume'i nuppu enam.

Saab teha nii et on

Suurem seotud probleem on siin see #6

**Comment by urmasnimetu** [comment]
Mitmendat korda vaadates tekkis igatsus, et kui video alguses käima panna (heli nupule vajutades või "vaata filmi"), siis võiks sinna tegelikult juba kohe ilmuda ka Home, Rewind, Pause ja FF nupud (samast hetkest, kui heliga video käima läheb). On neid keeruline lisada?

**Comment by rix133** [comment]
kõige lihtsam on teha nii, et need nupud (Home, Rewind, Pause ja FF) on kogu aeg olemas, ma saan aru et sa tahaks et need tekiks kui heli sisse lülitada kohe. Vaata filmi lülitab need juba praegu sisse minu meelest.

**Comment by urmasnimetu** [comment]
jah, vaata filmi nr 2 lülitab need sisse (see, mis viib edasi). Esmakordne vaatamine lülitab sisse heli ja viskab algusesse.
