### ISSUE TITLE
Video algust ei kuule

### ISSUE THREAD

**Issue by urmasnimetu** [rix133/amanda#12]
Kuna video algab ilma helita (ja võib oletada, et inimene ei jõua reageerida 4 sekundiga), siis 

lähevad sisuliselt kaduma Amanda esimesd laused ("Tere, minu nimi on Amanda, ma läheb täna operatsioonile"),

kuna hilisem loop'is ta kordab ainult viimast lauset ("Kui tahad näha, mis toimuma hakkab, vajuta sellele nupule siin").

Kas oleks võimalik teha nii, et kui sa esimese klõpsu teed (heli nupp sisse vms), siis viskab ta sind ikkagi jõuga video algusesse - st et ei ole võimalik esimesi lauseid mitte kuulda?

(Testitud Windows Chromega)

**Comment by rix133** [comment]
on küll võimalik, aga kas siis peaks üldse mängima hakkama ise vt #6

**Comment by urmasnimetu** [comment]
Minu arust võib küll mängida.
