### ISSUE TITLE
Operatsiooniõed hangusid

### ISSUE THREAD

**Issue by urmasnimetu** [rix133/amanda#13]
Esimesel vaatamisel hangus video valikus "operatsiooniõed" - video jäi seisma ja "Pause" nupp läks alla. Kõiki nuppe sai vajutada (liikusid üles-alla), aga midagi ei juhtunud. Ainus võimalus pääseda oli kogu lehele Refresh teha.

Teisel vaatamisel sama muret polnud.

(Testitud Windows Chrome peal).

**Comment by rix133** [comment]
Huvitav probleem, kõlab nagu brauser oleks kokku jooksnud vms. Ühesõnaga ilmselt koodist mitte sõltuv jama.

**Comment by rix133** [comment]
Õnnestus korra ka sama olukord tekitada, kuidas täpselt ei tea ja miks see juhtus ei tea ka. Tean vaid, et miskipärast ei suuda videopalyer videt enam edasi mängida ERROR  a la ` dom Exeption video.play() was interupted by a call to pause()`
