### ISSUE TITLE
Avalehe suurus

### ISSUE THREAD

**Issue by urmasnimetu** [rix133/amanda#14]
Linki avades oli kaader suurem kui brauseri aken, ning heli nupp jäi tegelikult brauseri serva taha, nii et seda polnud näha. 
Näha oli "Vaata filmi" nupp.

Võibolla see probleem kaob Embedimisega ära?

**Comment by rix133** [comment]
jah, embedimisega peaks see ära kaduma. Video võtab 100% brauseri akna laiusest ja kõrguse arvutab sellest. Nii on tagatud et külgede suhe on õige.
