### ISSUE TITLE
Video lõpp

### ISSUE THREAD

**Issue by urmasnimetu** [rix133/amanda#16]
Video ei jää lõpus (peale lõpukirju) seisma, vaid mängib edasi - tuleb kaalumise video, kust liigub uuesti haiglasse registreerimise juurde.
Selle asemel peaks viimane kaader lihtsalt seisma jääma (ning "Edasi" nupp ära kaduma).

Testitud Windows 10 Chrome'i peal.

**Comment by urmasnimetu** [comment]
Video jääb lõpus küll seisma, aga natuke liiga hilja: jääb näitama kaalumise video algust.

Võiks hanguda kaadril pärast lõpukirju, mil ilmub jälle alguse pealkiri (00:14:42,20).

See on sama kaader, mis on video alguses 00:00:54,12 peal. Sellega tuli mul uus mõte, et võibolla video võikski sealt lõpust visata algusesse tagasi (tiitri kaadrile) ning seal pausi peale minna? (st et kui uueti Play vajutad, siis hakkab 00:00:54,12 pealt algusanimatsioon jooksma.).

**Comment by rix133** [comment]
l. Sellega tuli mul uus mõte, et võibolla video võikski sealt lõpust visata algusesse tagasi (tiitri kaadrile) ning seal pausi peale minna? (st et kui uueti Play vajutad, siis hakkab 00:00:54,12 pealt algusanimatsioon jooksma.).

**Comment by urmasnimetu** [comment]
Ee ma mõtlesin, et viskab küll algusesse aga jääb pausile - st ei hakka kohe video jooksma, enne kui oled pausi ära vajutanud.
