### ISSUE TITLE
Edasi/tagasikerimise nupud

### ISSUE THREAD

**Issue by urmasnimetu** [rix133/amanda#19]
Mõlemad versioonid: aeg-ajalt ei toimi edasi/tagasikerimise nupud, vajab refreshimist.

**Comment by rix133** [comment]
Kas oleks võimalik saada vähe täpsemat infot mis tingimistes (mis seade, mis internet, mis nuppe järejst vajutades) see juhtub?

**Comment by rix133** [comment]
see võib olla seotud [B-frame](https://en.wikipedia.org/wiki/Video_compression_picture_types)'idega pakkimisel, 
neid saab keelata: [infot](https://video.stackexchange.com/questions/15800/how-can-i-set-the-first-frame-of-a-video-to-an-i-frame-and-the-rest-to-p-frames)
mis aga tähendab ilmselt suuremaid videofaile.
Võimaik et probleem esineb ainult vanemates brauserites, [sarane probleem](https://github.com/video-dev/hls.js/issues/1811), on esinenud varasemalt ja peaks olema juba lahenenud nüüdseks, seega võib olla hoopis miskit muud.

**Comment by urmasnimetu** [comment]
Ma saavutasin selle Firefox 83.0-iga - kui väga palju edasi-tagsi nuppe klõpsisin, siis ühel hetkel ta jäi pausi peale ja enam edasi-tagasi ei liikunud. 

Lasin natuke seista, vajutasin Play, lasin 30 sekundit mängida, ja siis edasi-nupp töötas vanaviisi edasi.

**Comment by rix133** [comment]
Ok, ma pakuks et ma ei hakka seda lahendama. Pole aimugi kuidas parandada ausalt öeldes. Kõlab nagu netiteenuse pakkuja ei suuda faile serveerida vahepeal kuna liiga palju on päringuid.

**Comment by urmasnimetu** [comment]
Minul esines probleem kasutades Windows 10 ja Google Chrome brauserit. Kuid hetkel probleemi korrata ei õnnestu, tundub, et see on lahenenud.

Tervitades
Hans-Erik Ehrlich
