### ISSUE TITLE
Videos algab heli enne teksti lõigus "mänguasjad"

### ISSUE THREAD

**Issue by rix133** [rix133/amanda#20]
Probleem juba algvideo failis ajal 00:14:29 mõlemas keeles (eesti ja vene) @urmasnimetu hea oleks kui helis algaks tekst paar kaadrit pärast videopildi algust.

**Comment by urmasnimetu** [comment]
Oli jah videofailis kogemata jäänud auk kahe lõigu vahele. Vabandan.
Kohendasin videofaili, nii et b6i_m2ngunurk asub nüüd vahemikus 00:14:27,16 - 00:14:39,80
(videfailis jääb auk 00:14:39,80-00:14:42:20 vahele).
