### ISSUE TITLE
Vene voice over mõõtmise ja kaalumise nupu alumises lõigus

### ISSUE THREAD

**Issue by sveeta** [rix133/amanda#4]
VOs on imelik ebaloogiline cut: "...необходимо знать, сколько ты весишь / то можно измерить ..." See on nagu "... hädavajalik on teada, palju sa kaalud / siis sind võib kaaluda..."

**Comment by urmasnimetu** [comment]
Venekeelne versioon kaalumise juures kaotas paar sõna ilmselt ära.

**Comment by rix133** [comment]
Urmaselt saadud videos on juba see probleem failis ~00:14:00 ajal

**Comment by urmasnimetu** [comment]
Parandasin videofaili.
