### ISSUE TITLE
Luubid operatsiooniruumis

### ISSUE THREAD

**Issue by sveeta** [rix133/amanda#5]
Kui vaadata mitte-full-screenis, siis luubid on justkui õiges kohas. Fullscreeniga nad sõidavad ülesse. Nt. monitoori luup on peaaegu moonitorist väljas, kõige ülemisem nupp (lambid), on peaaegu video servas.  

Tegelikult on sama asi ka muudes stseenides. Nt järgmises stseenis on pulsoksimeeter ja kateeter fullscreeniga üldsegi möödas.

**Comment by rix133** [comment]
See probleem on tingitud probleemist #7
